# Generated by Django 3.2.16 on 2023-02-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20230223_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
