# Generated by Django 3.2.16 on 2023-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20230223_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('payment', 'Payment'), ('deposit', 'Deposit')], max_length=20)),
                ('transaction_channel', models.CharField(blank=True, choices=[('card', 'Card'), ('wallet', 'Wallet'), ('bank', 'Bank')], max_length=20, null=True)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('refunded', 'Refunded')], max_length=20)),
                ('sender_account_name', models.CharField(max_length=255)),
                ('sender_account_number', models.CharField(max_length=50)),
                ('sender_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sender_account_balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sender_account_balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receiver_account_name', models.CharField(max_length=255)),
                ('receiver_account_number', models.CharField(max_length=50)),
                ('receiver_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('receiver_account_balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receiver_account_balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_description', models.TextField(blank=True, null=True)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
